# Generated by Django 4.2.2 on 2023-08-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('u_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_user', models.CharField(max_length=100)),
                ('c_email', models.EmailField(max_length=254)),
                ('c_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=200)),
                ('capacity', models.CharField(max_length=100)),
                ('bed', models.CharField(max_length=100)),
                ('services', models.TextField()),
            ],
        ),
    ]
