# Generated by Django 4.2.2 on 2023-08-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_reservation_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='adult',
            field=models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='child',
            field=models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='persons',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='request',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.DateField(max_length=50),
        ),
    ]
