# Generated by Django 4.2.2 on 2023-08-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_reservation_adult_reservation_child_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='check_out_date',
        ),
    ]
