# Generated by Django 4.2.2 on 2023-08-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_date_remove_reservation_check_in_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments_user',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='adult',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='child',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='persons',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='size',
        ),
    ]
