# Generated by Django 4.2.3 on 2023-07-05 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='client_last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
    ]
